apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plow-agent-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plow-agent
  labels:
    app: plow-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plow-agent
  template:
    metadata:
      labels:
        app: plow-agent
    spec:
      containers:
        - name: plow-agent
          image: ghcr.io/jackharrhy/plow-agent:latest
          args: ["--run", "--server", "https://plow.jackharrhy.dev"]
          env:
            - name: PLOW_NAME
              value: "your-name-here"
            - name: PLOW_DATA_DIR
              value: "/data"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plow-agent-data
